--- #YAML:1.0
name:                         Test-Smoke-Metabase
version:                      0.22
abstract:                     Metabase interface for Test::Smoke
license:                      perl
author:
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:                 Author
distribution_type:            module
provides:
    Test::Smoke::Metabase:
        file:                 lib/Test/Smoke/Metabase.pm
        version:              0.22
    Test::Smoke::Fact::SmokeID:
        file:                 lib/Test/Smoke/Fact/SmokeID.pm
        version:              0.011
    Test::Smoke::Fact::Node:
        file:                 lib/Test/Smoke/Fact/Node.pm
        version:              0.011
    Test::Smoke::Fact::Build:
        file:                 lib/Test/Smoke/Fact/Build.pm
        version:              0.010
    Test::Smoke::Fact::Config:
        file:                 lib/Test/Smoke/Fact/Config.pm
        version:              0.011
    Test::Smoke::Fact::Result:
        file:                 lib/Test/Smoke/Fact/Result.pm
        version:              0.010
    Test::Smoke::Metabase::Transport:
        file:                 lib/Test/Smoke/Metabase/Transport.pm
        version:              0.01
requires:
    perl:                     5.006
    base:                     2.14
    Carp:                     0
    JSON:                     2
    Metabase::Client::Simple: 0.008
    Metabase::Fact::Hash:     0.020
    Metabase::Report:         0.020
    Metabase::User::Profile:  0.020
    Metabase::User::Secret:   0.020
recommends:
    perl:                     5.014001
    base:                     2.16
    JSON:                     2.53
configure_requires:
    ExtUtils::MakeMaker:      0
test_requires:
    Test::Harness:            0
    Test::More:               0
resources:
    license:                  http://dev.perl.org/licenses/
    repository:               http://repo.or.cz/w/Test-Smoke-Metabase.git
meta-spec:
    version:                  1.4
    url:                      http://module-build.sourceforge.net/META-spec-v1.4.html
