--- #YAML:1.0
name:                         Test::Smoke::Metabase
version:                      0.03
abstract:                     Metabase interface for Test::Smoke
license:                      perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:                 Author
distribution_type:            module
provides:
    Test::Smoke::Metabase:
        file:                 lib/Test/Smoke/Metabase.pm
        version:              0.03
    Test::Smoke::Fact::SmokeID:
        file:                 lib/Test/Smoke/Fact/SmokeID.pm
        version:              0.002
    Test::Smoke::Fact::TestEnvironment:
        file:                 lib/Test/Smoke/Fact/TestEnvironment.pm
        version:              0.002
    Test::Smoke::Fact::SmokeConfig:
        file:                 lib/Test/Smoke/Fact/SmokeConfig.pm
        version:              0.002
    Test::Smoke::Fact::TestResult:
        file:                 lib/Test/Smoke/Fact/TestResult.pm
        version:              0.003
    Test::Smoke::Metabase::Transport:
        file:                 lib/Test/Smoke/Metabase/Transport.pm
        version:              0.01
requires:     
    perl:                     5.006
    base:                     2.14
    Carp:                     0
    Digest::MD5:              0
    JSON:                     2
    Metabase::Client::Simple: 0.004
    Metabase::Fact::Hash:     0.003
    Metabase::Fact::String:   0.003
    Metabase::Report:         0.003
    Metabase::User::Profile:  0.006
    Metabase::User::Secret:   0.006
recommends:
    perl:                     5.010001
configure_requires:
    ExtUtils::MakeMaker:      0
build_requires:
    perl:                     5.006
    Test::Harness:            0
    Test::More:               0
resources:
    license:                  http://dev.perl.org/licenses/
    repository:               http://repo.or.cz/r/Test-Smoke-Metabase.git
meta-spec:
    version:                  1.4
    url:                      http://module-build.sourceforge.net/META-spec-v1.4.html
